-- MySQL Script generated by MySQL Workbench
-- Fri Jun 28 20:09:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema compra_teste
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `compra_teste` ;

-- -----------------------------------------------------
-- Schema compra_teste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compra_teste` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `compra_teste` ;

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cliente` (
  `id_cliente` INT(4) NOT NULL,
  `nome_cliente` VARCHAR(50) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `tel_comercial` VARCHAR(11) NULL,
  `tel_celular` VARCHAR(12) NOT NULL,
  `email_cliente` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `detalhes_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detalhes_pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `detalhes_pedido` (
  `id_pedido` INT(4) NOT NULL,
  `id_produto` INT(4) NULL,
  `qatd-produto_total` INT(3) NULL,
  `preco_total` VARCHAR(10) NULL,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_categoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_categoria` (
  `nome_categoria` INT NOT NULL,
  `descricao_categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nome_categoria`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_pedido` (
  `id_pedido` INT(4) NOT NULL,
  `data_pedido` DATE NULL,
  `id_cliente` INT(4) NULL,
  `detalhes_pedido_id_pedido` INT(4) NOT NULL,
  PRIMARY KEY (`id_pedido`, `detalhes_pedido_id_pedido`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_produto` (
  `idtb_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(50) NOT NULL,
  `descricao_produto` VARCHAR(45) NOT NULL,
  `preco_produto` VARCHAR(10) NOT NULL,
  `qua_prodt_estoque` INT(4) NOT NULL,
  `nome_categ` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idtb_produto`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
