-- MySQL Script generated by MySQL Workbench
-- Thu Jul  4 19:28:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `escola` ;

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `escola` ;

-- -----------------------------------------------------
-- Table `Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Aluno` (
  `RA` INT(4) NOT NULL AUTO_INCREMENT,
  `nome_aluno` VARCHAR(45) NOT NULL,
  `sobre_aluno` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `status` TINYINT NOT NULL,
  `id_turma` INT(4) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `id_curso` INT(4) NOT NULL,
  `nome_pai` VARCHAR(50) NOT NULL,
  `nome_mae` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `whatsapp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RA`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Departamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Departamento` (
  `cod_Departamento` INT(4) NOT NULL AUTO_INCREMENT,
  `nome_departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_Departamento`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Disciplina` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Disciplina` (
  `id_disciplina` INT(4) NOT NULL,
  `nome_Disciplina` VARCHAR(20) NOT NULL,
  `cod_Departamento` INT(4) NOT NULL,
  `carga_horaria` INT(4) NOT NULL,
  `Descricao` VARCHAR(50) NOT NULL,
  `Num_alunos` INT(4) NOT NULL,
  PRIMARY KEY (`id_disciplina`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Professor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Professor` (
  `id_Professor` INT(4) NOT NULL,
  `nome_professor` VARCHAR(45) NOT NULL,
  `sobrenome_professor` VARCHAR(50) NOT NULL,
  `status` TINYINT NOT NULL,
  `cod_Departamento` INT(4) NOT NULL,
  PRIMARY KEY (`id_Professor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aluno_disc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aluno_disc` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aluno_disc` (
  `RA` INT(4) NOT NULL,
  `id_disciplina` INT(4) NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `curso` (
  `id_curso` INT(4) NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(40) NOT NULL,
  `cod_Departamento` INT(4) NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `curso_Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso_Disciplina` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `curso_Disciplina` (
  `id_curso` INT(4) NOT NULL,
  `id_disciplina` INT(4) NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `depende`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `depende` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `depende` (
  `id_disciplina` INT(4) NOT NULL,
  `possui_cod_disciplina` INT(4) NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `disc_hist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disc_hist` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `disc_hist` (
  `id_historico` INT(4) NOT NULL,
  `id_disciplina` INT(4) NOT NULL,
  `nota` INT(4) NOT NULL,
  `frequencia` INT(4) NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `endereco_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `endereco_aluno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `endereco_aluno` (
  `id_endereco_aluno` INT(4) NOT NULL AUTO_INCREMENT,
  `RA` INT(4) NOT NULL,
  `id_tipo_endereco` INT(4) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT(4) NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_endereco_aluno`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `historico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `historico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `historico` (
  `id_historico` INT(4) NOT NULL AUTO_INCREMENT,
  `RA` INT(4) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_final` DATE NOT NULL,
  PRIMARY KEY (`id_historico`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `prof_Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prof_Disciplina` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `prof_Disciplina` (
  `id_Professor` INT(4) NOT NULL,
  `id_Disciplinas` INT(4) NOT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `telefone_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefone_aluno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `telefone_aluno` (
  `id_telefone_aluno` INT(4) NOT NULL AUTO_INCREMENT,
  `RA` INT(4) NOT NULL,
  `id_tipo_telefone` INT(4) NOT NULL,
  `Num_telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_telefone_aluno`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipo_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_endereco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipo_endereco` (
  `id_tipo_endereco` INT(4) NOT NULL AUTO_INCREMENT,
  `tipo_endereco` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_tipo_endereco`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipo_telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_telefone` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipo_telefone` (
  `id_tipo_telefone` INT(4) NOT NULL AUTO_INCREMENT,
  `tipo_telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipo_telefone`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turma` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `turma` (
  `id_turma` INT(4) NOT NULL AUTO_INCREMENT,
  `id_curso` INT(4) NOT NULL,
  `Período` VARCHAR(8) NOT NULL,
  `num_Alunos` INT(4) NOT NULL,
  `Data_inicio` DATE NOT NULL,
  `Data_fim` DATE NOT NULL,
  PRIMARY KEY (`id_turma`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
